
import Head from "next/head";

import Searchwrapper from "../components/search/searchwrapper";

import { NextPageWithLayout } from "./_app";


import CardCarrousel from "../components/ui/cardcarrousel";
import Image from 'next/image'

import hero from '../../public/hero.jpg'

import hero1 from '../../public/hero1.png'
import hero2 from '../../public/hero2.png'
import hero3 from '../../public/hero3.png'








const Home: NextPageWithLayout = () => {

  

  return (
    <>
      <Head>
        <title>Dari</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
     
        
<main className="  flex flex-col  relative top-24 md:px-3 lg:px:6 ">
<h1 className="m-auto font-mono">Finding your next home , never been easier!</h1>


<div style={{
      backgroundImage: `url(${hero2.src})`,
      backgroundSize:'contain' ,
       backgroundPosition: 'center', 
       backgroundRepeat:'no-repeat'
    }}    className="mt-0 h-[80vh] w-full flex justify-center">

 
    <Searchwrapper/>
  
</div>




  <h1>properties for sell : </h1>
<div className="flex justify-center  md:w-[96vw] w-[93vw] ">
  <CardCarrousel type={'sell'} />
</div> 


<h1>properties for Rent : </h1>
<div className="flex justify-center  md:w-[96vw] w-[93vw] ">
  <CardCarrousel type={'Rent'} />
</div> 


<h1>Poeoples looking fo CoRental : </h1>
<div className="flex justify-center  md:w-[96vw] w-[93vw] ">
  <CardCarrousel type={'CoRental'} />
</div> 

 
</main>
      
      
    </>
  );
};

export default  Home;

